name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Swagger ui action
          id: swagger-ui-action
          uses: pjoc-team/swagger-ui-action@v0.0.2
          with:
            dir: './'
            pattern: '*.yaml'
            debug: 'true'
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: swagger-ui